on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2019
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
          fetch-depth: 0
          submodules: true

      - name: Prepare envars
        run: |
          echo "COMMIT_HASH=$("${{ github.sha }}".SubString(0, 8))" >> $env:GITHUB_ENV
          echo "APP_VERSION=$((Select-String -Path "loader\Program.cs" -Pattern 'VERSION = "(.+)"' -AllMatches).Matches.Groups[1].Value)" >> $env:GITHUB_ENV

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
          run_install: |
            - recursive: true

      - name: Build preload plugins
        run: |
          cd plugins
          pnpm install
          pnpm build

      - name: Build solution
        run: |
          mkdir bin
          echo "${{ env.APP_VERSION }}+${{ env.COMMIT_HASH }}" >> bin/version
          msbuild pengu.sln /t:Restore,Build /m /p:Configuration=Release /p:Platform=x64

      - name: Upload build outputs
        uses: actions/upload-artifact@v4
        with:
          name: pengu-v${{ env.APP_VERSION }}-${{ env.COMMIT_HASH }}
          path: |
            bin/*.exe
            bin/*.dll
            bin/version
